### ISSUE TITLE
希望增加负载均衡证书相关api

### ISSUE THREAD

**Issue by fivesmallq** [yunify/qingcloud-cli#20]
最近想使用Let's Encrypt的证书替换之前的付费证书，想做自动续期，结合这个工具：https://github.com/Neilpang/acme.sh 想加上青云的qingcloud-cli做个自动续期的工具，结果发现cli里居然没有相关的api，自己对python不太熟悉，请问这个工具还有人维护吗？没有的话，我就考虑用熟悉的java实现了先。

**Comment by Sunight** [comment]
你好，cli 目前版本还没有证书的命令，这个会加上，预计本周末更新。届时会再次告知。

**Comment by fivesmallq** [comment]
好的多谢，证书相关命令和负载均衡监听器操作证书命令就可以满足需求，不过还有一个cdn证书更新的问题，工单询问了下，说内部有了还没开放，不知道能否加上，因为一般更新证书是负载均衡和CDN一起

**Comment by Sunight** [comment]
我问了同事，这个近期还没有计划。这周末会先更新证书和负载均衡器相关 cli 命令。

**Comment by fivesmallq** [comment]
好的，多谢。

**Comment by Sunight** [comment]
你好，cli 和 sdk 都已更新，请通过 pip 下载最新版本（sdk 1.2.2，cli 1.3.2）

你的需求相关命令是：

- 查看证书：qingcloud iaas describe-server-certificates
- 创建证书：qingcloud iaas create-server-certificate
- 更新负载均衡器某个监听器的证书：qingcloud iaas  modify-loadbalancer-listener-attributes
- 使得负载均衡器的改动生效：qingcloud iaas update-loadbalancers

**Comment by fivesmallq** [comment]
@Sunight @SimonLuo 非常感谢，尤其看到最后提交时间。。。 
我这边测试下

**Comment by fivesmallq** [comment]
@Sunight 您好，有个问题，在使用qingcloud iaas modify-loadbalancer-listener-attributes的时候，如何绑定多个证书？因为很多时候，一个https监听器，会有多个证书。

**Comment by fivesmallq** [comment]
@Sunight 找到了，可以用逗号分割，建议说明文档里写清楚一点

**Comment by Sunight** [comment]
好的，会更新下 cli 的 help 提示这点。
